// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

const FALLBACK_SUPABASE_URL = "https://placeholder.supabase.co";
const FALLBACK_SUPABASE_KEY = "placeholder-key";

const isValidUrl = (value: unknown): value is string => {
  if (typeof value !== "string" || value.trim() === "") return false;

  try {
    new URL(value);
    return true;
  } catch {
    return false;
  }
};

const supabaseUrl = isValidUrl(SUPABASE_URL) ? SUPABASE_URL : FALLBACK_SUPABASE_URL;
const supabaseKey = typeof SUPABASE_PUBLISHABLE_KEY === "string" && SUPABASE_PUBLISHABLE_KEY.trim() !== ""
  ? SUPABASE_PUBLISHABLE_KEY
  : FALLBACK_SUPABASE_KEY;

if (!isValidUrl(SUPABASE_URL) || supabaseKey === FALLBACK_SUPABASE_KEY) {
  console.warn(
    "Supabase is not fully configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY in Vercel."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: typeof window !== "undefined" ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
